on:
  [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pytest flake8 black isort

      # Run isort and black BEFORE flake8 so code is auto-formatted before lint check
      - name: Run isort
        run: isort .

      - name: Auto-formatter (black)
        run: black .

      - name: Run tests
        run: pytest

      - name: Python Linter (flake8)
        run: flake8